;; ==========================================
;; BML Linear IR - Opcode Macros (Zero Memory!)
;; ==========================================

(let (;; --- Control Flow & Stack ---
      (OP_LABEL (macro () '1))
      (OP_JMP   (macro () '2))
      (OP_JZ    (macro () '3))
      (OP_CALL  (macro () '4))
      (OP_RET   (macro () '5))
      (OP_PUSH  (macro () '6))
      (OP_SET2  (macro () '7))
      (OP_POPR8 (macro () '8))

      ;; --- Memory & Environment ---
      (OP_LDIMM (macro () '10))
      (OP_LDMEM (macro () '11))
      (OP_LDGLB (macro () '12))
      (OP_STMEM (macro () '13))

      ;; --- Hardware Primitives ---
      (OP_ADD   (macro () '20))
      (OP_SUB   (macro () '21))
      (OP_MUL   (macro () '22))
      (OP_DIV   (macro () '23))
      (OP_CAR   (macro () '24))
      (OP_CDR   (macro () '25))
      (OP_CONS  (macro () '26))
      (OP_EQL   (macro () '27))
      (OP_LT    (macro () '28))
      (OP_GT    (macro () '29))
      (OP_LE    (macro () '30))
      (OP_GE    (macro () '31))
      (OP_AND   (macro () '32))
      (OP_OR    (macro () '33))
      (OP_ASH   (macro () '34))
      (OP_SYS   (macro () '35))
      (OP_PEEK  (macro () '36))
      (OP_POKE  (macro () '37))
      (OP_POKEB (macro () '38))
      (OP_PEEKI (macro () '39))
      (OP_POKEI (macro () '40))
      (OP_NOT   (macro () '41))
      (OP_GETHP (macro () '42))
      (OP_STHEP (macro () '43))
      (OP_ALLOC (macro () '44))
      (OP_GTCHR (macro () '45))
      (OP_PTCHR (macro () '46))
      (OP_PTINT (macro () '47))
      (OP_PTHEX (macro () '48))
      (OP_PTCHK (macro () '49))

      ;; --- Control Flow & ABI Stack ---
      (OP_ADDSP (macro () '50))
      (OP_TCALL (macro () '51))
      (OP_POPAR (macro () '52))
      (OP_PSHAR (macro () '53))
      (OP_POPRA (macro () '54))
      (OP_ENTER (macro () '55))
      (OP_LDFNC (macro () '56))
      (OP_LDSTR (macro () '57))
      (OP_STGLB (macro () '58))
      (OP_DICT  (macro () '59)))
  1)
